version: '3.4'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181/kafka
      KAFKA_CREATE_TOPICS: "TestMeister:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  nudge-server:
    restart: always
    image: nudge-server
    build:
      context: ./services/nudge_server
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    command: hypercorn -b 0.0.0.0 server:app
    environment:
      - PYTHONUNBUFFERED=0
    env_file:
      - .env
  nudge-client:
    image: nudge-client
    build:
      context: ./services/nudge_client
      dockerfile: Dockerfile
    volumes:
      - './services/nudge_client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development