version: '3.4'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181/kafka
      KAFKA_CREATE_TOPICS: "testtopic1:1:1"
    links:
      - zookeeper:zk
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  nudge-server:
    restart: always
    image: nudge-server
    build:
      context: ./services/nudge_server
      dockerfile: Dockerfile
    volumes:
      - './services/nudge_server/nudge_client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - "6066:6066"
    environment:
      - PYTHONUNBUFFERED=0
      - NODE_ENV=development
    env_file:
      - .env